# Generated by Django 5.0 on 2024-02-14 09:15

import django.db.models.deletion
import web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensitiveDataPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('pattern', models.CharField(max_length=128, validators=[web.models.validate_regex_group])),
            ],
        ),
        migrations.CreateModel(
            name='DataLeak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
                ('message', models.TextField()),
                ('message_id', models.UUIDField()),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.sensitivedatapattern')),
            ],
            options={
                'unique_together': {('pattern', 'message_id')},
            },
        ),
    ]
